server {
    listen 80;
    listen [::]:80;
    server_name isoc.or.id;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_tokens off;

    server_name isoc.or.id;
    root /var/www/html/public;
    index index.php index.html;

    # Ganti path SSL ke Let's Encrypt
    ssl_certificate     /etc/letsencrypt/live/isoc.or.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/isoc.or.id/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}