server {
    listen 80;
    listen [::]:80;
    server_name isoc.or.id;

    # Untuk verifikasi Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}